<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class SupplierInvoiceWorkflowNotification extends Notification
{
    use Queueable;

    public function __construct(
        private readonly string $subjectLine,
        private readonly string $message,
        private readonly int $quotationId,
    ) {
    }

    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject($this->subjectLine)
            ->greeting('Hello '.$notifiable->name.',')
            ->line($this->message)
            ->action('Open evaluation', route('admin.evaluations.show', $this->quotationId))
            ->line('This message was generated by the Shishi Footsteps evaluation workflow.');
    }
}
