<?php $__env->startSection('title','Live Chat Inbox'); ?>
<?php $__env->startSection('content'); ?>
<?php if (isset($component)) { $__componentOriginalad67f78bf768badc17b2fc4005a4f8bf = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginalad67f78bf768badc17b2fc4005a4f8bf = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.admin.top-bar','data' => ['title' => 'Live Chat Inbox','description' => 'Website visitor conversations','addButton' => false,'search' => false]] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('admin.top-bar'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['title' => 'Live Chat Inbox','description' => 'Website visitor conversations','addButton' => \Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute(false),'search' => \Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute(false)]); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginalad67f78bf768badc17b2fc4005a4f8bf)): ?>
<?php $attributes = $__attributesOriginalad67f78bf768badc17b2fc4005a4f8bf; ?>
<?php unset($__attributesOriginalad67f78bf768badc17b2fc4005a4f8bf); ?>
<?php endif; ?>
<?php if (isset($__componentOriginalad67f78bf768badc17b2fc4005a4f8bf)): ?>
<?php $component = $__componentOriginalad67f78bf768badc17b2fc4005a4f8bf; ?>
<?php unset($__componentOriginalad67f78bf768badc17b2fc4005a4f8bf); ?>
<?php endif; ?>
<?php echo $__env->make('admin.partials.flash', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<div class="chat-admin-shell">
    <aside class="chat-list"><div class="chat-list-tabs"><a href="<?php echo e(route('admin.chat.index')); ?>">All</a><a href="<?php echo e(route('admin.chat.index',['status'=>'open'])); ?>">Open</a><a href="<?php echo e(route('admin.chat.index',['status'=>'closed'])); ?>">Closed</a></div><?php $__empty_1 = true; $__currentLoopData = $conversations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $conversation): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a href="<?php echo e(route('admin.chat.index',['conversation'=>$conversation->id,'status'=>request('status')])); ?>#conversation-<?php echo e($conversation->id); ?>" class="chat-list-item"><span><?php echo e(strtoupper(substr($conversation->visitor_name ?: 'Guest',0,1))); ?></span><div><strong><?php echo e($conversation->visitor_name ?: 'Website guest'); ?></strong><small><?php echo e($conversation->visitor_email ?: 'No email yet'); ?></small></div><?php if($conversation->unread): ?><b><?php echo e($conversation->unread); ?></b><?php endif; ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="empty-cell">No website chats yet.</p><?php endif; ?></aside>
    <main class="chat-conversations"><?php $__currentLoopData = $conversations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $conversation): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><article id="conversation-<?php echo e($conversation->id); ?>" class="chat-thread"><header><div><strong><?php echo e($conversation->visitor_name ?: 'Website guest'); ?></strong><small><?php echo e($conversation->visitor_email); ?> · <?php echo e(ucfirst($conversation->status)); ?> · <?php echo e($conversation->last_message_at); ?></small></div><?php if($conversation->status==='open'): ?><form method="POST" action="<?php echo e(route('admin.chat.close',$conversation->id)); ?>"><?php echo csrf_field(); ?><button class="button button-secondary">Close chat</button></form><?php endif; ?></header><div class="chat-thread-messages"><?php $__currentLoopData = $conversation->messages; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $message): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="chat-bubble <?php echo e($message['sender']==='admin'?'agent':'visitor'); ?>"><small><?php echo e($message['sender']==='admin'?($message['agent'] ?: 'Shishi team'):'Visitor'); ?> · <?php echo e($message['time']); ?></small><p><?php echo e($message['body']); ?></p></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php if($conversation->status==='open'): ?><form class="chat-reply" method="POST" action="<?php echo e(route('admin.chat.reply',$conversation->id)); ?>"><?php echo csrf_field(); ?><textarea name="message" placeholder="Write a helpful reply…" required></textarea><button class="button button-primary"><i data-lucide="send"></i>Reply</button></form><?php endif; ?></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></main>
</div>
<?php $__env->startPush('styles'); ?><style>.chat-admin-shell{display:grid;grid-template-columns:280px 1fr;gap:14px}.chat-list,.chat-thread{background:#fff;border:1px solid var(--line);border-radius:10px}.chat-list-tabs{padding:10px;display:flex;gap:5px;border-bottom:1px solid var(--line)}.chat-list-tabs a{padding:6px 9px;background:#f2f5f3;border-radius:5px;font-size:8px;font-weight:700}.chat-list-item{padding:10px;display:flex;align-items:center;gap:9px;border-bottom:1px solid #edf0ee}.chat-list-item>span{width:31px;height:31px;display:grid;place-items:center;color:#fff;background:#50691d;border-radius:50%;font-weight:800}.chat-list-item div{min-width:0;flex:1}.chat-list-item strong,.chat-list-item small{display:block}.chat-list-item small{margin-top:2px;color:#849088;font-size:7px}.chat-list-item b{width:20px;height:20px;display:grid;place-items:center;color:#fff;background:#e14b29;border-radius:50%;font-size:7px}.chat-conversations{display:grid;gap:12px}.chat-thread>header{padding:12px 15px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.chat-thread header strong,.chat-thread header small{display:block}.chat-thread header small{margin-top:3px;color:#849088;font-size:7px}.chat-thread-messages{min-height:150px;max-height:440px;padding:14px;display:flex;flex-direction:column;gap:8px;overflow:auto;background:#f7f8f6}.chat-bubble{max-width:72%;padding:9px 11px;background:#fff;border-radius:10px 10px 10px 2px;box-shadow:0 2px 8px #dde3df}.chat-bubble.agent{align-self:flex-end;color:#fff;background:#50691d;border-radius:10px 10px 2px 10px}.chat-bubble small{font-size:6px;opacity:.7}.chat-bubble p{margin:3px 0 0;font-size:9px;line-height:1.5}.chat-reply{padding:10px;display:grid;grid-template-columns:1fr auto;gap:8px}.chat-reply textarea{min-height:55px;padding:9px;border:1px solid var(--line);border-radius:7px;resize:vertical}@media(max-width:760px){.chat-admin-shell{grid-template-columns:1fr}.chat-list{max-height:260px;overflow:auto}}</style><?php $__env->stopPush(); ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\shishifootsteps\safari\resources\views/admin/chat/index.blade.php ENDPATH**/ ?>