<?php $__env->startSection('title', 'Flight Ticket Bookings'); ?>
<?php $__env->startSection('content'); ?>
<?php if (isset($component)) { $__componentOriginalad67f78bf768badc17b2fc4005a4f8bf = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginalad67f78bf768badc17b2fc4005a4f8bf = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.admin.top-bar','data' => ['title' => 'Flight Bookings','description' => 'Aviation','addLabel' => 'New Flight Booking','addRoute' => ''.e(route('admin.flights.store')).'','searchPlaceholder' => 'Search flights...']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('admin.top-bar'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['title' => 'Flight Bookings','description' => 'Aviation','addLabel' => 'New Flight Booking','addRoute' => ''.e(route('admin.flights.store')).'','searchPlaceholder' => 'Search flights...']); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginalad67f78bf768badc17b2fc4005a4f8bf)): ?>
<?php $attributes = $__attributesOriginalad67f78bf768badc17b2fc4005a4f8bf; ?>
<?php unset($__attributesOriginalad67f78bf768badc17b2fc4005a4f8bf); ?>
<?php endif; ?>
<?php if (isset($__componentOriginalad67f78bf768badc17b2fc4005a4f8bf)): ?>
<?php $component = $__componentOriginalad67f78bf768badc17b2fc4005a4f8bf; ?>
<?php unset($__componentOriginalad67f78bf768badc17b2fc4005a4f8bf); ?>
<?php endif; ?>
<?php echo $__env->make('admin.partials.flash', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<div class="ops-two-column flight-layout">
<section class="ops-panel ops-form-panel">
    <div class="ops-panel-title"><div><h2><?php echo e($editing ? 'Edit flight booking' : 'New flight request'); ?></h2><p>Use exact details from the airline reservation.</p></div></div>
    <form method="POST" action="<?php echo e($editing ? route('admin.flights.update', $editing->id) : route('admin.flights.store')); ?>"><?php echo csrf_field(); ?> <?php if($editing): ?> <?php echo method_field('PUT'); ?> <?php endif; ?>
        <div class="ops-form-grid">
            <label class="span-2">Client<select name="client_id"><option value="">Walk-in / not linked</option><?php $__currentLoopData = $clients; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $client): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($client->id); ?>" <?php if(old('client_id', $editing->client_id ?? '') == $client->id): echo 'selected'; endif; ?>><?php echo e($client->name); ?> — <?php echo e($client->email); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label>Passenger name<input name="passenger_name" value="<?php echo e(old('passenger_name', $editing->passenger_name ?? '')); ?>" required></label>
            <label>Passenger type<select name="passenger_type"><?php $__currentLoopData = ['adult','child','infant']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if(old('passenger_type', $editing->passenger_type ?? 'adult') === $value): echo 'selected'; endif; ?>><?php echo e($value); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label>Passport number<input name="passport_number" value="<?php echo e(old('passport_number', $editing->passport_number ?? '')); ?>"></label>
            <label>Airline<input name="airline" value="<?php echo e(old('airline', $editing->airline ?? '')); ?>" placeholder="Kenya Airways" required></label>
            <label>Flight number<input name="flight_number" value="<?php echo e(old('flight_number', $editing->flight_number ?? '')); ?>" placeholder="KQ 482" required></label>
            <label>Flight type<select name="flight_type"><?php $__currentLoopData = ['domestic','international','charter']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if(old('flight_type', $editing->flight_type ?? request('type', 'domestic')) === $value): echo 'selected'; endif; ?>><?php echo e($value); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label>Cabin class<select name="cabin_class"><?php $__currentLoopData = ['economy','premium_economy','business','first']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('cabin_class', $editing->cabin_class ?? 'economy') === $value): echo 'selected'; endif; ?>><?php echo e(ucwords(str_replace('_', ' ', $value))); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label>Origin IATA<input name="origin_code" maxlength="3" value="<?php echo e(old('origin_code', $editing->origin_code ?? 'NBO')); ?>" required></label>
            <label>Destination IATA<input name="destination_code" maxlength="3" value="<?php echo e(old('destination_code', $editing->destination_code ?? '')); ?>" required></label>
            <label>Departure<input type="datetime-local" name="departure_at" value="<?php echo e(old('departure_at', isset($editing) && $editing ? \Carbon\Carbon::parse($editing->departure_at)->format('Y-m-d\TH:i') : '')); ?>" required></label>
            <label>Arrival<input type="datetime-local" name="arrival_at" value="<?php echo e(old('arrival_at', isset($editing) && $editing ? \Carbon\Carbon::parse($editing->arrival_at)->format('Y-m-d\TH:i') : '')); ?>" required></label>
            <label>PNR / locator<input name="pnr" value="<?php echo e(old('pnr', $editing->pnr ?? '')); ?>"></label>
            <label>Ticket number<input name="ticket_number" value="<?php echo e(old('ticket_number', $editing->ticket_number ?? '')); ?>"></label>
            <label>Baggage allowance<input name="baggage_allowance" value="<?php echo e(old('baggage_allowance', $editing->baggage_allowance ?? '23kg checked + 7kg cabin')); ?>"></label>
            <label>Supplier / consolidator<input name="supplier" value="<?php echo e(old('supplier', $editing->supplier ?? '')); ?>"></label>
            <label>Base fare<input type="number" step="0.01" name="base_fare" value="<?php echo e(old('base_fare', $editing->base_fare ?? '')); ?>" required></label>
            <label>Taxes & fees<input type="number" step="0.01" name="taxes" value="<?php echo e(old('taxes', $editing->taxes ?? 0)); ?>" required></label>
            <label>Markup %<input type="number" step="0.01" name="markup_percent" value="<?php echo e(old('markup_percent', $editing->markup_percent ?? 10)); ?>" required></label>
            <label>Currency<input name="currency" maxlength="3" value="<?php echo e(old('currency', $editing->currency ?? 'USD')); ?>" required></label>
            <label>Payment deadline<input type="date" name="payment_deadline" value="<?php echo e(old('payment_deadline', $editing->payment_deadline ?? '')); ?>"></label>
            <label>Payment status<select name="payment_status"><?php $__currentLoopData = ['unpaid','part_paid','paid','refunded']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('payment_status', $editing->payment_status ?? 'unpaid') === $value): echo 'selected'; endif; ?>><?php echo e(ucwords(str_replace('_', ' ', $value))); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label>Booking status<select name="booking_status"><?php $__currentLoopData = ['requested','on_hold','confirmed','ticketed','cancelled','completed']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('booking_status', $editing->booking_status ?? 'requested') === $value): echo 'selected'; endif; ?>><?php echo e(ucwords(str_replace('_', ' ', $value))); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label class="span-2">Ticketing notes<textarea name="notes" rows="4"><?php echo e(old('notes', $editing->notes ?? '')); ?></textarea></label>
        </div>
        <div class="ops-form-footer"><?php if($editing): ?><a class="button button-secondary" href="<?php echo e(route('admin.flights.index')); ?>">Cancel</a><?php endif; ?><button class="button button-primary"><i data-lucide="save"></i><?php echo e($editing ? 'Update booking' : 'Create request'); ?></button></div>
    </form>
</section>
<section class="ops-panel">
    <form class="ops-filters" method="GET"><label class="ops-search"><i data-lucide="search"></i><input name="search" value="<?php echo e(request('search')); ?>" placeholder="Passenger, PNR, ticket or flight"></label><select name="type"><option value="">All flight types</option><?php $__currentLoopData = ['domestic','international','charter']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if(request('type') === $type): echo 'selected'; endif; ?>><?php echo e($type); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><select name="status"><option value="">All statuses</option><?php $__currentLoopData = ['requested','on_hold','confirmed','ticketed','cancelled','completed']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if(request('status') === $status): echo 'selected'; endif; ?>><?php echo e($status); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><button class="button button-primary">Filter</button></form>
    <div class="table-wrap"><table class="ops-table"><thead><tr><th>Request / passenger</th><th>Flight</th><th>Schedule</th><th>PNR / ticket</th><th>Fare</th><th>Selling</th><th>Payment</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    <?php $__empty_1 = true; $__currentLoopData = $flights; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $flight): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($flight->request_reference); ?></strong><small><?php echo e($flight->passenger_name); ?> · <?php echo e(ucfirst($flight->passenger_type)); ?> · <?php echo e($flight->client_name); ?></small></td><td><strong><?php echo e($flight->airline); ?> <?php echo e($flight->flight_number); ?></strong><small><?php echo e($flight->origin_code); ?> → <?php echo e($flight->destination_code); ?> · <?php echo e(ucwords(str_replace('_', ' ', $flight->cabin_class))); ?></small></td><td><?php echo e(\Carbon\Carbon::parse($flight->departure_at)->format('d M Y H:i')); ?><small>Arrive <?php echo e(\Carbon\Carbon::parse($flight->arrival_at)->format('d M H:i')); ?></small></td><td><?php echo e($flight->pnr ?: 'Not assigned'); ?><small><?php echo e($flight->ticket_number ?: 'Not ticketed'); ?></small></td><td><span class="buy-price"><?php echo e($flight->currency); ?> <?php echo e(number_format($flight->base_fare + $flight->taxes, 2)); ?></span><small><?php echo e(number_format($flight->markup_percent, 1)); ?>% markup</small></td><td><strong class="sell-price"><?php echo e($flight->currency); ?> <?php echo e(number_format($flight->selling_total, 2)); ?></strong></td><td><span class="ops-pill <?php echo e($flight->payment_status === 'paid' ? 'ops-pill--green' : 'ops-pill--red'); ?>"><?php echo e(ucwords(str_replace('_', ' ', $flight->payment_status))); ?></span></td><td><span class="ops-pill ops-pill--blue"><?php echo e(ucwords(str_replace('_', ' ', $flight->booking_status))); ?></span></td><td><div class="ops-actions"><a href="<?php echo e(route('admin.flights.index', ['edit' => $flight->id])); ?>"><i data-lucide="square-pen"></i></a><form method="POST" action="<?php echo e(route('admin.flights.destroy', $flight->id)); ?>" onsubmit="return confirm('Delete this flight booking?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button><i data-lucide="trash-2"></i></button></form></div></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="9" class="empty-cell">No flight bookings match this filter.</td></tr><?php endif; ?>
    </tbody></table></div><div class="ops-pagination"><?php echo e($flights->links()); ?></div>
</section>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\user\Documents\xamp\htdocs\safari\resources\views\admin\flights\index.blade.php ENDPATH**/ ?>