<?php

return [
    'pages' => [
        'global' => ['label' => 'Global website settings', 'fields' => [
            'company_name' => ['label'=>'Company name','type'=>'text','default'=>'Shishi Footsteps'],
            'phone' => ['label'=>'Phone / WhatsApp','type'=>'text','default'=>'+254 725 346 022'],
            'email' => ['label'=>'General email','type'=>'text','default'=>'info@shishifootsteps.com'],
            'bookings_email' => ['label'=>'Bookings email','type'=>'text','default'=>'bookings@shishifootsteps.com'],
            'address' => ['label'=>'Office address','type'=>'text','default'=>'Nairobi, Kenya'],
            'footer_heading' => ['label'=>'Newsletter heading','type'=>'text','default'=>'Get safari inspiration'],
            'footer_text' => ['label'=>'Newsletter text','type'=>'textarea','default'=>'Get travel ideas, destination tips and new safari journeys sent to your inbox.'],
        ]],
        'home' => ['label' => 'Homepage content', 'fields' => [
            'hero_label'=>['label'=>'Hero label','type'=>'text','default'=>'Private African journeys'],
            'hero_title'=>['label'=>'Hero title','type'=>'textarea','default'=>'Travel Africa, your way.'],
            'hero_text'=>['label'=>'Hero text','type'=>'textarea','default'=>'Tailor-made safaris, trusted local expertise and thoughtful details from the first idea to the journey home.'],
            'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>'images/itineraries/kenya-family-cover.webp'],
            'intro_label'=>['label'=>'Introduction label','type'=>'text','default'=>'Tailor-made African Safaris'],
            'intro_title'=>['label'=>'Introduction title','type'=>'text','default'=>'Premium journeys crafted around you'],
            'intro_text'=>['label'=>'Introduction text','type'=>'textarea','default'=>'Shishi Footsteps is a curated travel design company specializing in premium, tailor-made safaris across East Africa. Rather than selling fixed packages, we build every itinerary from scratch based on your interests, pace, comfort level, and travel goals.'],
            'destinations_title'=>['label'=>'Destinations heading','type'=>'text','default'=>'Kenya, Tanzania, Uganda, Rwanda, South Africa, Namibia, Botswana'],
            'experiences_title'=>['label'=>'Experiences heading','type'=>'text','default'=>'Shape each day around what moves you.'],
            'safaris_title'=>['label'=>'Safaris heading','type'=>'text','default'=>'Safari packages ready to become personal.'],
            'cta_title'=>['label'=>'Final CTA title','type'=>'text','default'=>'Let Us Design Your Safari Journey'],
            'cta_text'=>['label'=>'Final CTA text','type'=>'textarea','default'=>'Tell us your preferences and our specialists will shape a tailor-made itinerary built from scratch around you.'],
            'cta_image'=>['label'=>'Final CTA image','type'=>'image','default'=>'images/itineraries/tanzania-crater-day.webp'],
            'youtube_id'=>['label'=>'YouTube hero video ID','type'=>'text','default'=>'1CYVG70ZbyQ'],
        ]],
        'about' => ['label'=>'About page','fields'=>[
            'hero_label'=>['label'=>'Hero label','type'=>'text','default'=>'About Shishi Footsteps'], 'hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'Crafted with care, guided by Africa.'],
            'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'We are a curated travel design company specializing in premium, tailor-made safari experiences across East Africa.'],
            'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1800&q=82&fm=webp'],
            'intro_title'=>['label'=>'Introduction title','type'=>'text','default'=>'Luxury is personal, not loud.'], 'intro_text'=>['label'=>'Introduction copy','type'=>'textarea','default'=>'Shishi Footsteps is a curated travel design company specializing in premium, tailor-made experiences across East Africa. We build every itinerary around your interests, pace, comfort level, and travel goals.'],
            'mission_title'=>['label'=>'Mission title','type'=>'text','default'=>'To be the premier provider of luxury safari experiences in Africa'], 'mission_text'=>['label'=>'Mission text','type'=>'textarea','default'=>'Renowned for exceptional wildlife journeys alongside Africa\'s natural beauty and rich cultural heritage.'],
            'vision_title'=>['label'=>'Vision title','type'=>'text','default'=>'Travel that leaves more than footprints'], 'vision_text'=>['label'=>'Vision text','type'=>'textarea','default'=>'To deliver unparalleled journeys blending world-class safari experiences with wildlife, pristine landscapes, and vibrant cultures.'],
            'cta_title'=>['label'=>'CTA title','type'=>'text','default'=>'Let Us Design Your Journey'], 'cta_text'=>['label'=>'CTA text','type'=>'textarea','default'=>'Tell us what you are dreaming of, and we will shape a safari with the right destinations, pace, guides and lodges — built from scratch around you.'], 'cta_image'=>['label'=>'CTA image','type'=>'image','default'=>'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1800&q=82&fm=webp'],
        ]],
        'contact' => ['label'=>'Contact page','fields'=>[
            'hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'Let us begin with a conversation.'], 'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'Call, email or send the inquiry form. Your request will be saved in the CRM for specialist follow-up.'],
            'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>'https://images.unsplash.com/photo-1504432842672-1a79f78e4084?auto=format&fit=crop&w=1800&q=82&fm=webp'], 'intro_title'=>['label'=>'Section title','type'=>'text','default'=>'Safari planning should feel calm from the first message.'], 'intro_text'=>['label'=>'Section text','type'=>'textarea','default'=>'Tell us what you are imagining. We will help you choose the right destination, season, lodges and pace.'],
        ]],
        'destinations'=>['label'=>'Destinations page','fields'=>['hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'The wild, chosen with intention.'],'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'We specialize in extraordinary African destinations, from wildlife-rich plains to gorilla forests, desertscapes and coastal escapes.'],'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1800&q=82&fm=webp']]],
        'safaris'=>['label'=>'Safaris page','fields'=>['hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'Private safaris with a polished plan.'],'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'Start with a published itinerary, then let our specialists refine the route, lodges and pace around you.'],'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1800&q=82&fm=webp']]],
        'accommodations'=>['label'=>'Accommodation page','fields'=>['hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'Stay close to the wild, never far from comfort.'],'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'We select lodges and camps for guiding, location, atmosphere, food, privacy and the feeling they leave behind.'],'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>'https://images.unsplash.com/photo-1547970810-dc1eac37d174?auto=format&fit=crop&w=1800&q=82&fm=webp']]],
        'experiences'=>['label'=>'Experiences page','fields'=>['hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'The best safari days are never generic.'],'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'Choose the activities that make your journey feel alive, from quiet forest treks to private sundowners.'],'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1800&q=82&fm=webp']]],
        'itineraries'=>['label'=>'Itineraries page','fields'=>['hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'Routes with rhythm, not rush.'],'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'Published safari programs from our planning studio, ready for specialists to tailor around you.'],'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>'https://images.unsplash.com/photo-1523805009345-7448845a9e53?auto=format&fit=crop&w=1800&q=82&fm=webp']]],
        'blog'=>['label'=>'Blog page','fields'=>['hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'Field notes for better journeys.'],'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'Ideas, seasonal insight and safari inspiration from the Shishi Footsteps planning desk.'],'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?auto=format&fit=crop&w=1800&q=82&fm=webp']]],
        'booking'=>['label'=>'Booking page','fields'=>['hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'Plan Your Safari'],'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'Share a few details and our safari team will shape the journey around you.'],'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>'https://images.unsplash.com/photo-1504432842672-1a79f78e4084?auto=format&fit=crop&w=1800&q=82&fm=webp']]],
        'faqs'=>['label'=>'FAQs page','fields'=>[
            'hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'Frequently Asked Questions'],
            'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'Everything you need to know about planning your African golf safari and travel experiences.'],
            'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>''],
            'editorial_title'=>['label'=>'Editorial title','type'=>'text','default'=>'Your questions, answered'],
            'editorial_text'=>['label'=>'Editorial text','type'=>'textarea','default'=>'Whether you are planning a golf tour, combining a safari with your rounds, or arranging a complete African holiday, we are here to make the process effortless. Below you will find answers to the most common questions our travellers ask.'],
        ]],
        'golf'=>['label'=>'Golf page','fields'=>[
            'hero_label'=>['label'=>'Hero label','type'=>'text','default'=>'African Golf Holidays'],
            'hero_title'=>['label'=>'Hero title','type'=>'text','default'=>'Beyond the Fairways'],
            'hero_subtitle'=>['label'=>'Hero subtitle','type'=>'textarea','default'=>'Championship golf, carefully timed tee sheets and smooth travel between Africa\'s most rewarding courses.'],
            'hero_image'=>['label'=>'Hero image','type'=>'image','default'=>''],
            'youtube_id'=>['label'=>'YouTube video ID','type'=>'text','default'=>'iG5nlWiP9Ro'],
            'intro_label'=>['label'=>'Intro label','type'=>'text','default'=>'Tee Off With Shishi Footsteps'],
            'intro_title'=>['label'=>'Intro title','type'=>'text','default'=>'A golf safari designed around your game'],
            'intro_text'=>['label'=>'Intro text','type'=>'textarea','default'=>'Shishi Footsteps designs luxury golf safaris across Africa. We combine access to premier golf courses with unforgettable safari adventures, relaxing coastal escapes, premium accommodation and meaningful cultural experiences. Every itinerary is thoughtfully designed around the traveller\'s interests, travel style and preferred pace. From the first tee time to the final sunset, our team manages every detail to create a seamless and memorable African journey.'],
            'services_label'=>['label'=>'Services section label','type'=>'text','default'=>'The Shishi Difference'],
            'services_title'=>['label'=>'Services section title','type'=>'text','default'=>'Everything a travelling golfer needs'],
            'packages_label'=>['label'=>'Packages section label','type'=>'text','default'=>'Golf Itineraries'],
            'packages_title'=>['label'=>'Packages section title','type'=>'text','default'=>'Choose a fairway, then make it yours'],
            'courses_label'=>['label'=>'Courses section label','type'=>'text','default'=>'Premier Courses'],
            'courses_title'=>['label'=>'Courses section title','type'=>'text','default'=>'Africa\'s standout fairways'],
            'complete_label'=>['label'=>'Complete service label','type'=>'text','default'=>'Complete Golf Service'],
            'complete_title'=>['label'=>'Complete service title','type'=>'text','default'=>'Everything around your round, handled'],
            'cta_label'=>['label'=>'CTA label','type'=>'text','default'=>'Your Golf Safari'],
            'cta_title'=>['label'=>'CTA title','type'=>'text','default'=>'Where Passion for Golf Meets the Spirit of Adventure'],
            'cta_text'=>['label'=>'CTA text','type'=>'textarea','default'=>'Tell us your preferred courses, travel dates and handicap. Our specialists will create a personalised African golf safari around you.'],
            'cta_image'=>['label'=>'CTA image','type'=>'image','default'=>''],
        ]],
    ],
];
