<?php

return [
    [
        'id' => 'planning',
        'label' => 'Planning a proposal',
        'display' => 'Planning',
        'image' => 'https://images.unsplash.com/photo-1418065460487-3e41a6c84dc5?auto=format&fit=crop&w=1800&q=84&fm=webp',
        'image_alt' => 'Mist over a quiet forest at first light',
        'items' => [
            ['q' => 'How do I request a private proposal?', 'a' => 'Share your destination, dates, travellers and travel style on our proposal form. A Shishi Footsteps trip advisor will reply with questions if needed, then a written itinerary and quote. There is no obligation and no booking fee to enquire.'],
            ['q' => 'What will the proposal include?', 'a' => 'A typical proposal covers the suggested route, nights in each area, lodge or camp ideas, included game drives or activities, internal flights or road transfers, park or permit fees where relevant, and a clear price. Golf tee times, beach endings and special occasions are written in when you ask for them.'],
            ['q' => 'How quickly will a specialist reply?', 'a' => 'Most enquiries receive a first response within one working day. A full proposal usually follows within a few working days, depending on lodge availability, gorilla permits and how detailed the brief is.'],
            ['q' => 'Can I customise an existing safari idea?', 'a' => 'Yes. Published itineraries are starting points. We reshape nights, lodges, pace, guiding style, golf and beach add-ons around your dates and budget.'],
            ['q' => 'Do you sell fixed group packages?', 'a' => 'We specialise in private, tailor-made travel rather than departing group tours. Solo travellers, couples, families and private groups are all welcome.'],
            ['q' => 'How far in advance should I book?', 'a' => 'For Great Migration camps, gorilla permits and peak Christmas or Easter dates, book 6–12 months ahead. Shoulder seasons can work with a shorter lead time. Early planning still gives the best choice of rooms and internal flights.'],
            ['q' => 'Is there a minimum stay?', 'a' => 'A meaningful safari usually needs at least four nights in one wildlife area. Seven to ten days allows two habitats. Ten to fourteen days suits multi-country travel, golf or a beach ending.'],
            ['q' => 'Can I combine more than one country?', 'a' => 'Yes. Kenya with Tanzania, Uganda or Rwanda gorilla trekking, and South Africa with a Cape Town or wine-country chapter are all common. We plan visas, flights and border logistics so the route stays calm.'],
            ['q' => 'Who designs my trip?', 'a' => 'A dedicated trip advisor shapes the route, then our operations team confirms lodges, permits and transfers. You keep one specialist conversation from first enquiry through travel.'],
            ['q' => 'Can I change the proposal after I receive it?', 'a' => 'Yes. Lodge swaps, extra nights, a slower pace or a golf round can be revised before you confirm. Availability is always the limit, not our willingness to reshape it.'],
        ],
    ],
    [
        'id' => 'destinations',
        'label' => 'Destinations',
        'display' => 'Countries',
        'image' => 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1800&q=84&fm=webp',
        'image_alt' => 'Open country at first light',
        'items' => [
            ['q' => 'Which countries does Shishi Footsteps plan?', 'a' => 'Kenya, Tanzania, Uganda, Rwanda, South Africa, Namibia and Botswana. These are the regions where we hold trusted lodge relationships and on-the-ground support.'],
            ['q' => 'What is the best time for an East African safari?', 'a' => 'East Africa works year-round. July to October is the classic dry and migration window in Kenya and Tanzania. January to March is excellent wildlife with fewer vehicles. Green season suits photography, birding and value, with more dramatic skies.'],
            ['q' => 'Can I see the Big Five?', 'a' => 'Kenya, Tanzania, South Africa, Rwanda’s Akagera and parts of Namibia and Botswana all offer strong Big Five or near-Big Five viewing. Sightings are never guaranteed; we choose habitats and seasons that give the best realistic chance.'],
            ['q' => 'Are safaris private?', 'a' => 'Most of our journeys are privately guided, with a vehicle and guide for your party. Private conservancies add night drives, walking and quieter vehicle numbers where the rules allow.'],
            ['q' => 'Do you offer fly-in safaris?', 'a' => 'Yes. Light-aircraft hops save long road days between remote camps. We mix flying and driving according to budget, time and how much of the landscape you want to see from the ground.'],
            ['q' => 'Can safari be combined with a beach holiday?', 'a' => 'Yes. Kenya’s coast, Zanzibar after Tanzania, and South Africa’s coastline all make natural endings. We leave honest recovery time between the last game drive and the first beach breakfast.'],
            ['q' => 'Do you arrange desert or remote-country travel?', 'a' => 'Yes. Northern Kenya, Namibia’s dunes and Damaraland, and Botswana’s pans are planned with specialist camps, scenic flights where useful, and realistic driving days.'],
        ],
    ],
    [
        'id' => 'kenya',
        'label' => 'Kenya',
        'display' => 'Kenya',
        'image' => 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=1800&q=84&fm=webp',
        'image_alt' => 'Lion in golden light',
        'items' => [
            ['q' => 'Why travel to Kenya with Shishi Footsteps?', 'a' => 'Kenya holds the Masai Mara, private conservancies, Amboseli elephants under Kilimanjaro, Samburu’s dry-country specialists, Laikipia rhino country and a warm Indian Ocean ending. We match parks to season rather than sending everyone on the same loop.'],
            ['q' => 'When should I visit the Masai Mara?', 'a' => 'July to October is the famous migration window, with river crossings possible but never promised on a given morning. Conservancies around the Mara work well year-round and stay quieter than the main reserve in peak months.'],
            ['q' => 'What makes a Kenya conservancy different?', 'a' => 'Private conservancies often allow off-road driving, night drives and walking. Vehicle numbers are managed, so the same wildlife feels more personal than a busy national-reserve circuit.'],
            ['q' => 'Is Amboseli worth including?', 'a' => 'Yes, especially for elephant herds and Kilimanjaro views when the mountain is out. It is compact, photogenic and pairs well with Tsavo or a coastal finish.'],
            ['q' => 'Can I add golf in Kenya?', 'a' => 'Yes. Windsor, Karen, Vipingo Ridge, Nyali and Diani courses all sit naturally beside safari or beach chapters. We book tee times around transfers so the days stay elegant rather than rushed.'],
        ],
    ],
    [
        'id' => 'tanzania',
        'label' => 'Tanzania & the migration',
        'display' => 'Tanzania',
        'image' => 'images/itineraries/tanzania-classic-cover.webp',
        'image_alt' => 'Open Tanzania plains at safari hour',
        'items' => [
            ['q' => 'Why is Tanzania a flagship safari country?', 'a' => 'Serengeti plains, Ngorongoro Crater, Tarangire elephants, southern wilderness in Ruaha or Nyerere, and a Zanzibar beach ending give Tanzania extraordinary range in one itinerary.'],
            ['q' => 'What is the Great Migration?', 'a' => 'More than a million wildebeest and zebra follow rain and grass between the Serengeti and the Masai Mara. It is a moving river of animals, not a single viewpoint. Camp location and month matter more than any photograph.'],
            ['q' => 'When are the river crossings?', 'a' => 'Northern Serengeti and Mara crossings are typically July to October, shifting with rainfall. Calving on the southern Serengeti plains is roughly December to March. We time camps to the herds, not a fixed postcard date.'],
            ['q' => 'What is special about Ngorongoro Crater?', 'a' => 'The crater floor packs lion, elephant, buffalo, flamingo lakes and, with luck, rhino into a collapsed caldera. We plan an early descent from a rim lodge and rarely make the crater the whole Tanzania story.'],
            ['q' => 'Is Tarangire worth visiting?', 'a' => 'Yes. Dry-season elephant concentrations, baobabs and a different texture from the Serengeti make Tarangire a strong first or last safari chapter.'],
            ['q' => 'Is Zanzibar a good safari ending?', 'a' => 'Yes. Stone Town, spice, and quiet beach lodges reset the senses after dusty game-drive days. We keep the transfer honest so you arrive ready to slow down.'],
        ],
    ],
    [
        'id' => 'gorillas',
        'label' => 'Uganda & Rwanda',
        'display' => 'Gorillas',
        'image' => 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1800&q=84&fm=webp',
        'image_alt' => 'Mountain forest gorilla country in the Virungas',
        'items' => [
            ['q' => 'Do you arrange gorilla trekking?', 'a' => 'Yes. We secure permits, forest lodges and logistics in Uganda’s Bwindi and Rwanda’s Volcanoes National Park. Permits are limited and should be booked early.'],
            ['q' => 'What is gorilla trekking actually like?', 'a' => 'You hike with rangers to a habituated family, then spend a carefully timed hour with them. Trails can be steep and muddy. Fitness helps, but the day is not a race; porters and a lodge the night before make it considered rather than athletic.'],
            ['q' => 'Uganda or Rwanda for gorillas?', 'a' => 'Rwanda is compact: Kigali to the volcanoes is a scenic drive, with strong lodges and easy add-ons such as golden monkeys or Akagera. Uganda often pairs Bwindi with chimpanzees, Queen Elizabeth or the Nile for a wider country story. We choose by dates, budget and what else you want to see.'],
            ['q' => 'What else can I do in Rwanda besides gorillas?', 'a' => 'Golden monkeys, Akagera savannah and Big Five game drives, Lake Ihema boats, Nyungwe chimpanzees and canopy walks, Twin Lakes, Kigali culture and championship golf.'],
            ['q' => 'What else can I do in Uganda?', 'a' => 'Kibale chimpanzees, tree-climbing lions and Kazinga boat time in Queen Elizabeth, Murchison Falls, Lake Mburo walking, Nile rafting and highland golf.'],
            ['q' => 'When is the best time to trek?', 'a' => 'Drier windows are roughly June to September and December to February. Rain does not cancel trekking; it changes the mud and the photographs. Permits remain the planning anchor in every month.'],
            ['q' => 'Is Rwanda safe for travellers?', 'a' => 'Rwanda is one of Africa’s most orderly tourism destinations, with well-managed parks and short transfer times. We still use vetted drivers, lodges and 24/7 support as we do everywhere.'],
        ],
    ],
    [
        'id' => 'south',
        'label' => 'South Africa, Namibia & Botswana',
        'display' => 'The south',
        'image' => 'images/itineraries/botswana-chobe-day.webp',
        'image_alt' => 'Chobe water and southern African wilderness',
        'items' => [
            ['q' => 'Why include South Africa?', 'a' => 'Cape Town, the Winelands, Garden Route and Greater Kruger or Sabi Sand private reserves can sit in one itinerary. Guiding standards are high, and golf, wine and coastline are easy to add.'],
            ['q' => 'When is the best safari season in South Africa?', 'a' => 'May to September is the dry Kruger window: thinner bush and strong game viewing. Cape Town’s brightest coastal months run roughly November to March. Whale season is the southern winter. We match those calendars rather than forcing one date on the whole country.'],
            ['q' => 'How do South African safaris differ from East Africa?', 'a' => 'Private reserves often allow off-road driving and fewer vehicles. Lodges lean into fine dining and short transfer times. Wildlife is concentrated, which is excellent for first-time safari travellers and families.'],
            ['q' => 'Can I add wine country or Cape Town?', 'a' => 'Yes. Stellenbosch, Franschhoek, Table Mountain, the Atlantic coast and the Garden Route all pair with a Kruger-edge safari if the flying days are planned cleanly.'],
            ['q' => 'What makes Namibia different?', 'a' => 'Namibia is landscape first: Sossusvlei dunes, desert-adapted elephant and rhino, Etosha waterholes and huge night skies. Distances are real, so we fly some legs and keep road days honest.'],
            ['q' => 'When should I visit Namibia?', 'a' => 'May to October is cooler and dry, with magnetic Etosha waterholes and kinder dune mornings. Summer heat inland is intense; the coast stays milder.'],
            ['q' => 'What is special about Botswana?', 'a' => 'Private Okavango concessions, mokoro and boat time when the flood is in, Chobe elephants, and quiet luxury camps. We match camps to the water, not the brochure.'],
            ['q' => 'When is Botswana’s flood season?', 'a' => 'Peak Okavango water is typically mid-year, even though rain fell months earlier upstream. Late dry season, roughly August to October, is superb for Chobe elephants, with heat as the trade-off.'],
        ],
    ],
    [
        'id' => 'days',
        'label' => 'Safari days & wildlife',
        'display' => 'On safari',
        'image' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=1800&q=84&fm=webp',
        'image_alt' => 'Leopard resting in warm light',
        'items' => [
            ['q' => 'What does a typical safari day look like?', 'a' => 'An early game drive, a long brunch and rest at camp, then an afternoon drive and sundowner. Wildlife is most active in the cooler hours. Private guiding lets you linger or return to camp when you wish.'],
            ['q' => 'What vehicles do you use?', 'a' => 'Custom 4x4 safari vehicles with pop-up roofs, maintained for photography and comfort. Your party usually has a private vehicle and a professional guide-driver.'],
            ['q' => 'Are walking safaris available?', 'a' => 'Yes, in selected conservancies and parks, led by trained walking guides. Walks focus on tracks, birds and the small details you miss from a vehicle.'],
            ['q' => 'Can I do a hot-air balloon safari?', 'a' => 'Yes, in the Masai Mara and Serengeti when weather and permits allow. Sunrise flights are followed by a bush breakfast. We book these as optional highlights, not as a guarantee of every dawn.'],
            ['q' => 'Are balloon and walking safaris safe?', 'a' => 'They run under strict operator rules with trained crews or armed walking guides in designated areas. We only add them where the season, age policy and fitness fit the travellers.'],
            ['q' => 'Can I hike or trek as well as safari?', 'a' => 'Yes. Options include crater rims, highland walks, Mount Kenya or Kilimanjaro approaches, and Rwanda’s forest trails. We keep trek days from colliding with long game-drive mornings.'],
            ['q' => 'Do you handle dietary requirements?', 'a' => 'Yes. We brief lodges on allergies, vegetarian, vegan, kosher-style and medical diets before you arrive. Remote camps still cook with care; very specialised needs are flagged early.'],
        ],
    ],
    [
        'id' => 'stays',
        'label' => 'Camps & lodges',
        'display' => 'Camps',
        'image' => 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?auto=format&fit=crop&w=1800&q=84&fm=webp',
        'image_alt' => 'Canvas safari tent at golden hour',
        'items' => [
            ['q' => 'What kind of accommodation do you book?', 'a' => 'Boutique tented camps, classic lodges, private conservancy houses, villas and the occasional exclusive-use camp. We choose for location, guiding, service and how each stay supports the full route — not only for pretty photographs.'],
            ['q' => 'What is a luxury tented camp?', 'a' => 'Canvas suites with proper beds, en-suite bathrooms, hot water and serious dining, set inside the bush. It feels closer to the night sounds than a hotel block, without giving up comfort.'],
            ['q' => 'Do camps have electricity and Wi-Fi?', 'a' => 'Most use solar or generators. Charging is standard. Wi-Fi is common in main areas and patchy in tents. We treat connectivity as a bonus, not a promise, in true wilderness.'],
            ['q' => 'Can I stay in a private conservancy or villa?', 'a' => 'Yes, where it lifts the experience: fewer vehicles, family space, or a celebration. Exclusive-use camps and villas need earlier booking.'],
            ['q' => 'Do you offer ultra-luxury or helicopter access?', 'a' => 'Yes, when it earns its place: scenic helicopter hops, private charters, and camps at the top of the market. We will also tell you when a simpler lodge in a better location is the wiser spend.'],
        ],
    ],
    [
        'id' => 'golf',
        'label' => 'Golf safaris',
        'display' => 'Golf',
        'image' => 'https://images.unsplash.com/photo-1530028828-25e8270793c5?auto=format&fit=crop&w=1800&q=84&fm=webp',
        'image_alt' => 'Quiet championship fairway at first light',
        'items' => [
            ['q' => 'What is a golf safari?', 'a' => 'Championship rounds paired with wildlife, coast or culture in the same journey. Mornings on the fairway, afternoons on a game drive or at the beach, with tee times booked before you fly.'],
            ['q' => 'Where do you play?', 'a' => 'Kenya, Rwanda, Uganda and South Africa are our core golf countries, with Namibia desert golf as a rare extra. We pick courses for conditioning, setting and how they sit next to safari lodges.'],
            ['q' => 'Do I need to bring clubs?', 'a' => 'Bring your own or hire quality rental sets. We arrange hire, carts, caddies and practice facilities so you are not improvising at the first tee.'],
            ['q' => 'Can non-golfers join?', 'a' => 'Yes. Spa mornings, city tours, cultural visits or extra safari time run in parallel so mixed groups still travel together.'],
            ['q' => 'Is golf suitable for beginners?', 'a' => 'Yes. We mix forgiving courses with a signature round, and can add a lesson. Handicap certificates are only needed where a club requires them.'],
            ['q' => 'Do you organise corporate or club groups?', 'a' => 'Yes. Tee sheets, scoring, gala dinners, branding and a safari or wine chapter can all sit in one private group programme.'],
        ],
    ],
    [
        'id' => 'who',
        'label' => 'Families, couples & special interest',
        'display' => 'Travellers',
        'image' => 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1800&q=84&fm=webp',
        'image_alt' => 'Canvas camp under a quiet night sky',
        'items' => [
            ['q' => 'Are safaris suitable for children?', 'a' => 'Yes, with the right camps. We choose family rooms or adjoining tents, private vehicles, and lodges with junior ranger programmes. Some walking safaris and gorilla treks have minimum ages.'],
            ['q' => 'What is the minimum age for gorilla trekking?', 'a' => 'Typically 15 in Rwanda and Uganda. We plan alternative forest or savannah days for younger children travelling with the family.'],
            ['q' => 'Do you design honeymoons?', 'a' => 'Yes. Private vehicles, bush dinners, quieter conservancies and a beach or wine ending are the usual grammar. We keep the itinerary spacious rather than packed.'],
            ['q' => 'Can I travel solo?', 'a' => 'Yes. Private guiding keeps the days flexible. We pay extra attention to lodge location, transfers and how evenings feel in camp.'],
            ['q' => 'Do you plan multi-generational trips?', 'a' => 'Yes. Different room types, a private vehicle, and a mix of shorter and longer activity days keep grandparents and children comfortable on the same route.'],
            ['q' => 'Can you plan wellness or recovery travel?', 'a' => 'Yes, including spa-led lodges, yoga time, and — where medically appropriate — recovery stays after treatment. Safari days are only added with medical clearance and a slower pace.'],
            ['q' => 'Do you arrange marathon or sports travel?', 'a' => 'Yes. Race logistics, altitude training bases in Kenya, and a safari or coast recovery chapter can be built around a sports calendar.'],
            ['q' => 'Can the trip support conservation or community visits?', 'a' => 'Yes, when they are genuine partnerships rather than staged stops. Park fees and the right camps already fund protection; we can add a well-run project visit where it fits.'],
        ],
    ],
    [
        'id' => 'practical',
        'label' => 'Visas, health & packing',
        'display' => 'Before you fly',
        'image' => 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1800&q=84&fm=webp',
        'image_alt' => 'A quiet trail at the start of a journey',
        'items' => [
            ['q' => 'Do I need a visa?', 'a' => 'It depends on nationality and country. Kenya, Tanzania, Uganda and Rwanda all use electronic visas or similar systems for many passports. We send a country-by-country note with your proposal; you remain responsible for applying on time.'],
            ['q' => 'What vaccinations are recommended?', 'a' => 'See a travel clinic well before departure. Yellow fever proof can be required depending on your route. Hepatitis A, typhoid and malaria prophylaxis are commonly discussed for East and Southern Africa.'],
            ['q' => 'Is safari travel safe?', 'a' => 'With a reputable operator, licensed guides and vetted lodges, safari travel is a well-established form of tourism. We provide pre-travel advice, monitored transfers and support while you are on the ground.'],
            ['q' => 'Do you provide meet-and-greet at the airport?', 'a' => 'Yes. A representative meets you after immigration and stays with the transfer until you are at the hotel or on the light aircraft.'],
            ['q' => 'Can you arrange private charters?', 'a' => 'Yes, from scheduled hops to private aircraft or helicopter, when time, remoteness or a celebration justifies it.'],
            ['q' => 'Do I need travel insurance?', 'a' => 'Yes. Comprehensive cover for medical treatment, evacuation, cancellation and valuables is essential. We do not sell insurance; we will tell you what the policy must include.'],
            ['q' => 'What should I pack?', 'a' => 'Neutral layers, a warm fleece for dawn drives, sun protection, broken-in walking shoes, and a camera. Soft-sided bags are required for most bush flights. A detailed packing note goes out with your final documents.'],
            ['q' => 'What currency should I bring?', 'a' => 'US dollars in good condition are widely useful for tips. Lodge extras may take card. Remote camps can be cash-only for curios. We include tipping guidance in your travel pack.'],
            ['q' => 'How does tipping work?', 'a' => 'Tipping is customary and discretionary. We suggest ranges for guides, camp teams, caddies and drivers so you are never guessing at the last sundowner.'],
            ['q' => 'What happens in an emergency?', 'a' => 'Lodges hold first-response plans. We work with flying-doctor and evacuation partners where the itinerary requires it. Insurance must cover evacuation; we coordinate the practical steps on the ground.'],
            ['q' => 'Do you provide 24/7 support while I travel?', 'a' => 'Yes. Your advisor and our operations team remain reachable for delays, lodge questions and changes that cannot wait until morning.'],
        ],
    ],
    [
        'id' => 'payment',
        'label' => 'Price, payment & policies',
        'display' => 'The details',
        'image' => 'images/itineraries/botswana-luxury-cover.webp',
        'image_alt' => 'A private camp at the edge of the wild',
        'items' => [
            ['q' => 'What is included in the price?', 'a' => 'Usually accommodation, meals as specified, park fees, safari activities, and transfers that appear in the itinerary. International flights and insurance are quoted separately unless you ask us to include them. Golf green fees and gorilla permits are itemised when they apply.'],
            ['q' => 'How much does a luxury safari cost?', 'a' => 'It varies with season, camp, private guiding and internal flights. As a guide, many private journeys sit from about $5,000 per person for a shorter circuit, with high-end migration, gorilla and exclusive-use camps well above that. Your proposal states a clear figure rather than a vague range.'],
            ['q' => 'Do you require a deposit?', 'a' => 'Yes. A deposit secures lodges and permits. The balance is due before travel on a schedule we set out in writing. Payment is typically by international bank transfer.'],
            ['q' => 'What is your cancellation policy?', 'a' => 'Terms follow the lodges and permit authorities on your route, which is why they are attached to the proposal rather than hidden in small print. Travel insurance should cover cancellation. We explain the dates before you pay a deposit.'],
            ['q' => 'Can I extend the trip once I am there?', 'a' => 'Often, if rooms and aircraft seats exist. Tell us as early as you can; wilderness camps fill quickly in peak months.'],
            ['q' => 'Do you send a pre-travel pack?', 'a' => 'Yes. Packing, health, visa links, tipping, contacts and a day-by-day outline go out once the trip is confirmed.'],
            ['q' => 'Why travel with Shishi Footsteps?', 'a' => 'Because the proposal is written around you: private guiding, lodges we actually trust, golf when you want it, and logistics that stay invisible. We stay on the journey with you, not only until the invoice is paid.'],
        ],
    ],
];
