<?php

/**
 * Traveller reviews for each destination section.
 * Photos are unique within a country page.
 */
return [
    'kenya' => [
        [
            'quote' => 'The Mara conservancy stay changed the whole trip. Private guiding, no crowding, and evenings that felt considered rather than scheduled. Shishi Footsteps wrote the days around us, not a brochure.',
            'name' => 'Amelia & James Hart',
            'from' => 'United Kingdom',
            'trip' => 'Nine-night Kenya conservancy safari',
            'image' => 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Game drive light on the Kenyan plains',
        ],
        [
            'quote' => 'Travelling with children can be noisy planning. Ours was not. Family tents, a private vehicle, and enough rest that the kids still wanted one more game drive. Amboseli and the coast sat together without feeling rushed.',
            'name' => 'Nia Okello',
            'from' => 'United States',
            'trip' => 'Kenya family safari and Diani ending',
            'image' => 'images/itineraries/kenya-family-cover.webp',
            'image_alt' => 'Open Kenya safari country',
        ],
        [
            'quote' => 'We asked for safari mornings and a proper round at Vipingo. Tee times, transfers and the last sundowner all landed. It felt like one journey, not two holidays glued together.',
            'name' => 'Daniel Crowe',
            'from' => 'Ireland',
            'trip' => 'Kenya golf safari',
            'image' => 'images/itineraries/kenya-coast-day.webp',
            'image_alt' => 'Kenya coast after safari',
        ],
    ],
    'tanzania' => [
        [
            'quote' => 'They timed the Serengeti camp to the herds, then gave us Ngorongoro as a single, early crater morning — not a checklist. The migration felt like weather: present, moving, never promised on a given hour.',
            'name' => 'Sophie Laurent',
            'from' => 'France',
            'trip' => 'Tanzania migration safari',
            'image' => 'images/itineraries/tanzania-classic-cover.webp',
            'image_alt' => 'Serengeti plains in Tanzania',
        ],
        [
            'quote' => 'Tarangire’s elephants and the crater rim stay were the chapters we still talk about. Logistics stayed invisible. That is rarer than people admit.',
            'name' => 'Marcus & Elena Voss',
            'from' => 'Germany',
            'trip' => 'Northern Tanzania private circuit',
            'image' => 'images/itineraries/tanzania-crater-day.webp',
            'image_alt' => 'Ngorongoro crater light',
        ],
        [
            'quote' => 'Zanzibar after the dust was the right kind of quiet. Stone Town one night, then a beach lodge with nothing to prove. Shishi left honest recovery time between the last game drive and the first swim.',
            'name' => 'Priya Menon',
            'from' => 'Singapore',
            'trip' => 'Serengeti and Zanzibar',
            'image' => 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Open East African sky',
        ],
    ],
    'uganda' => [
        [
            'quote' => 'The gorilla hour in Bwindi was steep, muddy and completely worth it. Permits, porters and the lodge the night before were handled before we ever thought to ask.',
            'name' => 'Hannah Reid',
            'from' => 'Canada',
            'trip' => 'Bwindi gorilla trek',
            'image' => 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Mountain forest in gorilla country',
        ],
        [
            'quote' => 'Queen Elizabeth’s boat time on the Kazinga and the chimps at Kibale made Uganda feel wider than a single trek. Our advisor kept the driving days honest.',
            'name' => 'Tomás Álvarez',
            'from' => 'Spain',
            'trip' => 'Uganda forests and savannah',
            'image' => 'https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Ugandan highland country',
        ],
        [
            'quote' => 'We added a round at Tooro between forest days. It should have been awkward. It was not. That is the Shishi difference: the itinerary still had a pulse.',
            'name' => 'Grace Nalwanga',
            'from' => 'Uganda / United Kingdom',
            'trip' => 'Uganda golf and wildlife',
            'image' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Forest light in Uganda',
        ],
    ],
    'rwanda' => [
        [
            'quote' => 'Kigali to the volcanoes is a beautiful drive, and the gorilla morning was as carefully paced as everyone said it would be. Golden monkeys the next day felt like a gift, not an add-on.',
            'name' => 'Claire Bennett',
            'from' => 'Australia',
            'trip' => 'Volcanoes National Park trek',
            'image' => 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Virunga forest',
        ],
        [
            'quote' => 'Akagera surprised us: real savannah, boat light on Lake Ihema, and a night that was quiet in the best way. Rwanda is compact, and Shishi used that well.',
            'name' => 'Kwame Boateng',
            'from' => 'Ghana',
            'trip' => 'Gorillas and Akagera',
            'image' => 'https://images.unsplash.com/photo-1517853782856-d7cc5de7a7fc?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Rwandan hills',
        ],
        [
            'quote' => 'We played Kigali Golf Resort, then went to the forest. Championship turf and mountain mist in the same week. The proposal read like someone had actually walked the days.',
            'name' => 'Helena Kruger',
            'from' => 'South Africa',
            'trip' => 'Rwanda championship golf week',
            'image' => 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Highland golf in Rwanda',
        ],
    ],
    'south-africa' => [
        [
            'quote' => 'Sabi Sand guiding was as good as we had hoped, and Cape Town afterwards had room to breathe. Wine country was not a rush through tasting rooms. It was lunch, light, and a late table.',
            'name' => 'Olivia Chen',
            'from' => 'Hong Kong',
            'trip' => 'Kruger-edge safari and Cape',
            'image' => 'https://images.unsplash.com/photo-1484318571209-661cf29a69c3?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Cape Town and Table Mountain',
        ],
        [
            'quote' => 'Private reserve nights, fewer vehicles, and a lodge that cooked as if it mattered. South Africa can feel easy. Shishi made it feel chosen.',
            'name' => 'Robert & Anne Fitzgerald',
            'from' => 'United States',
            'trip' => 'Greater Kruger private reserve',
            'image' => 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Safari day in South Africa',
        ],
        [
            'quote' => 'Garden Route golf, then a quiet coast. Tee sheets were protected, clubs arrived, and nobody was improvising at the first tee. That is all we wanted.',
            'name' => 'Ian MacLeod',
            'from' => 'Scotland',
            'trip' => 'South Africa golf travel',
            'image' => 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'South African fairway',
        ],
    ],
    'namibia' => [
        [
            'quote' => 'Sossusvlei at first light is a photograph you walk into. Distances in Namibia are real; Shishi flew the legs that would have stolen the days, and kept the road where the landscape deserved it.',
            'name' => 'Ingrid Holm',
            'from' => 'Sweden',
            'trip' => 'Dunes, Damaraland and Etosha',
            'image' => 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Namib dunes',
        ],
        [
            'quote' => 'Desert-adapted elephants, night skies, and a camp that understood silence. We did not want a busy safari. We were not given one.',
            'name' => 'Paul Okonkwo',
            'from' => 'Nigeria',
            'trip' => 'Namibia wilderness circuit',
            'image' => 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Open desert road in Namibia',
        ],
        [
            'quote' => 'Etosha waterholes in the dry months were magnetic. The itinerary never pretended Namibia is small. That honesty is why we will go back.',
            'name' => 'Marta Nowak',
            'from' => 'Poland',
            'trip' => 'Etosha and the coast',
            'image' => 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Wildlife at a waterhole',
        ],
    ],
    'botswana' => [
        [
            'quote' => 'The Delta was water, light and a camp that felt private without being precious. Mokoro time was slow in the way you hope Africa will be, and never is when the days are overpacked.',
            'name' => 'Charlotte & Ben Walsh',
            'from' => 'New Zealand',
            'trip' => 'Okavango private concession',
            'image' => 'images/itineraries/botswana-luxury-cover.webp',
            'image_alt' => 'Luxury camp in Botswana',
        ],
        [
            'quote' => 'Chobe elephants from the water, then Savuti for predators. Two camps, enough nights, no filler. Shishi matched the water, not the brochure.',
            'name' => 'Aisha Rahman',
            'from' => 'United Arab Emirates',
            'trip' => 'Chobe and the Delta',
            'image' => 'images/itineraries/botswana-chobe-day.webp',
            'image_alt' => 'Chobe river wilderness',
        ],
        [
            'quote' => 'We wanted quiet luxury and got it: small aircraft, a guide who could wait, and evenings that belonged to us. Botswana is expensive. This one earned it.',
            'name' => 'Henrik Sørensen',
            'from' => 'Denmark',
            'trip' => 'Botswana fly-in safari',
            'image' => 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?auto=format&fit=crop&w=1200&q=84&fm=webp',
            'image_alt' => 'Open Botswana sky',
        ],
    ],
];
