<?php

return [
    'requests' => ['admin.requests.index'],
    'request-list' => ['admin.requests.index'],
    'new-request' => ['admin.requests.create'],
    'pending-requests' => ['admin.requests.index', ['status' => 'new']],
    'converted-requests' => ['admin.requests.index', ['status' => 'converted']],
    'cancelled-requests' => ['admin.requests.index', ['status' => 'cancelled']],
    'travel-requests' => ['admin.leads.index'],
    'website-enquiry-analytics' => ['admin.leads.index'],
    'live-chat-inbox' => ['admin.chat.index'],
    'clients' => ['admin.records.index', ['slug' => 'clients-register']],
    'proposals' => ['admin.quotations.index'],
    'proposal-planning' => ['admin.proposal-planning.index'],
    'safari-programs' => ['admin.quotations.index'],
    'itineraries' => ['admin.itineraries.index'],
    'itinerary-list' => ['admin.itineraries.index'],
    'new-itinerary' => ['admin.itineraries.create'],
    'itinerary-days' => ['admin.itineraries.index'],
    'route-builder' => ['admin.itineraries.index'],
    'reusable-safari-programs' => ['admin.itineraries.index'],
    'published-website-itineraries' => ['admin.itineraries.index', ['status' => 'published']],
    'published-itineraries' => ['admin.itineraries.index', ['status' => 'published']],
    'planning-calendar' => ['admin.proposal-planning.index'],
    'draft-proposals' => ['admin.proposal-planning.index', ['stage' => 'planning']],
    'active-proposals' => ['admin.proposal-planning.index', ['stage' => 'planning', 'step' => 'quotation-check']],
    'confirmed-proposals' => ['admin.proposal-planning.index', ['stage' => 'confirmed']],
    'proposal-snapshots' => ['admin.quotations.index'],
    'proposal-tasks' => ['admin.records.index', ['slug' => 'proposal-tasks']],
    'flight-requests' => ['admin.flights.index'],
    'domestic-flights' => ['admin.flights.index', ['type' => 'domestic']],
    'international-flights' => ['admin.flights.index', ['type' => 'international']],
    'charter-flights' => ['admin.flights.index', ['type' => 'charter']],
    'flight-prices' => ['admin.flights.index'],
    'flight-reservation-status' => ['admin.flights.index'],
    'flight-suppliers' => ['admin.flights.index'],
    'activity-list' => ['admin.activities.index'],
    'activity-categories' => ['admin.activity-categories.index'],
    'activity-prices' => ['admin.activities.index'],
    'activity-availability' => ['admin.activities.index'],
    'activity-suppliers' => ['admin.suppliers.index', ['type' => 'activity']],
    'activity-translations' => ['admin.translations'],
    'activity-website-publishing' => ['admin.activities.index'],
    'accommodation-list' => ['admin.accommodations.index'],
    'new-accommodation' => ['admin.accommodations.create'],
    'rooms-ages' => ['admin.accommodations.index'],
    'manage-prices' => ['admin.accommodations.index'],
    'availability' => ['admin.reservations.index'],
    'accommodation-translations' => ['admin.translations'],
    'compare-accommodation-costs' => ['admin.accommodations.compare'],
    'reservations' => ['admin.reservations.index'],
    'reservation-invoices' => ['admin.evaluations.invoices'],
    'evaluations' => ['admin.evaluations.index'],
    'evaluation-dashboard' => ['admin.evaluations.overview'],
    'supplier-confirmations' => ['admin.reservations.index', ['status' => 'pending']],
    'vehicles' => ['admin.records.index', ['slug' => 'vehicle-register']],
    'daily-movements' => ['admin.records.index', ['slug' => 'daily-movements']],
    'driver-briefings' => ['admin.records.index', ['slug' => 'driver-briefings']],
    'payment-deadlines' => ['admin.reservations.index'],
    'supplier-payments' => ['admin.reservations.index'],
    'evaluated-invoices' => ['admin.evaluations.invoices', ['status' => 'payment_ready']],
    'invoices' => ['admin.evaluations.invoices'],
    'client-payments' => ['admin.quotations.index'],
    'profit-loss' => ['admin.quotations.index', ['status' => 'completed']],
    'supplier-list' => ['admin.suppliers.index'],
    'countries' => ['admin.countries.index'],
    'regions' => ['admin.countries.index'],
    'itinerary-templates' => ['admin.itinerary-templates.index'],
    'itinerary-template-list' => ['admin.itinerary-templates.index'],
    'new-itinerary-template' => ['admin.itinerary-templates.create'],
    'itinerary-builder' => ['admin.itinerary-builder.index'],
    'cms-pages' => ['admin.cms.index'],
    'home-page' => ['admin.cms.home-settings'],
    'seo-settings' => ['admin.cms.home-settings'],
    'seo-metadata' => ['admin.cms.home-settings'],
    'website-cms' => ['admin.cms.index'],
    'audit-logs' => ['admin.audit-logs.index'],
    'sales-report' => ['admin.reports.sales'],
    'booking-report' => ['admin.reports.bookings'],
    'supplier-report' => ['admin.reports.suppliers'],
    'activity-report' => ['admin.reports.activities'],
    'weekly-management-report' => ['admin.reports.weekly'],
    'kpi-dashboard' => ['admin.reports.kpi'],
    'executive-dashboard' => ['admin.executive-dashboard'],
    'bookings-list' => ['admin.bookings.index'],
    'new-booking' => ['admin.bookings.create'],
    'booking-management' => ['admin.bookings.index'],
    'payment-management' => ['admin.bookings.index'],
    'payment-links' => ['admin.bookings.index'],
    'leads-list' => ['admin.leads.index'],
    'crm-dashboard' => ['admin.leads.index'],
    'translation-manager' => ['admin.translations'],
    'users' => ['admin.users.index'],
    'roles-permissions' => ['admin.users.index'],
    'manage-2fa' => ['admin.two-factor.index'],
];
