@extends('layouts.admin')
@section('title','Live Chat Inbox')
@section('content')
<x-admin.top-bar title="Live Chat Inbox" description="Website visitor conversations" :addButton="false" :search="false" />
@include('admin.partials.flash')
<div class="chat-admin-shell">
    <aside class="chat-list"><div class="chat-list-tabs"><a href="{{ route('admin.chat.index') }}">All</a><a href="{{ route('admin.chat.index',['status'=>'open']) }}">Open</a><a href="{{ route('admin.chat.index',['status'=>'closed']) }}">Closed</a></div>@forelse($conversations as $conversation)<a href="{{ route('admin.chat.index',['conversation'=>$conversation->id,'status'=>request('status')]) }}#conversation-{{ $conversation->id }}" class="chat-list-item"><span>{{ strtoupper(substr($conversation->visitor_name ?: 'Guest',0,1)) }}</span><div><strong>{{ $conversation->visitor_name ?: 'Website guest' }}</strong><small>{{ $conversation->visitor_email ?: 'No email yet' }}</small></div>@if($conversation->unread)<b>{{ $conversation->unread }}</b>@endif</a>@empty<p class="empty-cell">No website chats yet.</p>@endforelse</aside>
    <main class="chat-conversations">@foreach($conversations as $conversation)<article id="conversation-{{ $conversation->id }}" class="chat-thread"><header><div><strong>{{ $conversation->visitor_name ?: 'Website guest' }}</strong><small>{{ $conversation->visitor_email }} · {{ ucfirst($conversation->status) }} · {{ $conversation->last_message_at }}</small></div>@if($conversation->status==='open')<form method="POST" action="{{ route('admin.chat.close',$conversation->id) }}">@csrf<button class="button button-secondary">Close chat</button></form>@endif</header><div class="chat-thread-messages">@foreach($conversation->messages as $message)<div class="chat-bubble {{ $message['sender']==='admin'?'agent':'visitor' }}"><small>{{ $message['sender']==='admin'?($message['agent'] ?: 'Shishi team'):'Visitor' }} · {{ $message['time'] }}</small><p>{{ $message['body'] }}</p></div>@endforeach</div>@if($conversation->status==='open')<form class="chat-reply" method="POST" action="{{ route('admin.chat.reply',$conversation->id) }}">@csrf<textarea name="message" placeholder="Write a helpful reply…" required></textarea><button class="button button-primary"><i data-lucide="send"></i>Reply</button></form>@endif</article>@endforeach</main>
</div>
@push('styles')<style>.chat-admin-shell{display:grid;grid-template-columns:280px 1fr;gap:14px}.chat-list,.chat-thread{background:#fff;border:1px solid var(--line);border-radius:10px}.chat-list-tabs{padding:10px;display:flex;gap:5px;border-bottom:1px solid var(--line)}.chat-list-tabs a{padding:6px 9px;background:#f2f5f3;border-radius:5px;font-size:8px;font-weight:700}.chat-list-item{padding:10px;display:flex;align-items:center;gap:9px;border-bottom:1px solid #edf0ee}.chat-list-item>span{width:31px;height:31px;display:grid;place-items:center;color:#fff;background:#50691d;border-radius:50%;font-weight:800}.chat-list-item div{min-width:0;flex:1}.chat-list-item strong,.chat-list-item small{display:block}.chat-list-item small{margin-top:2px;color:#849088;font-size:7px}.chat-list-item b{width:20px;height:20px;display:grid;place-items:center;color:#fff;background:#e14b29;border-radius:50%;font-size:7px}.chat-conversations{display:grid;gap:12px}.chat-thread>header{padding:12px 15px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.chat-thread header strong,.chat-thread header small{display:block}.chat-thread header small{margin-top:3px;color:#849088;font-size:7px}.chat-thread-messages{min-height:150px;max-height:440px;padding:14px;display:flex;flex-direction:column;gap:8px;overflow:auto;background:#f7f8f6}.chat-bubble{max-width:72%;padding:9px 11px;background:#fff;border-radius:10px 10px 10px 2px;box-shadow:0 2px 8px #dde3df}.chat-bubble.agent{align-self:flex-end;color:#fff;background:#50691d;border-radius:10px 10px 2px 10px}.chat-bubble small{font-size:6px;opacity:.7}.chat-bubble p{margin:3px 0 0;font-size:9px;line-height:1.5}.chat-reply{padding:10px;display:grid;grid-template-columns:1fr auto;gap:8px}.chat-reply textarea{min-height:55px;padding:9px;border:1px solid var(--line);border-radius:7px;resize:vertical}@media(max-width:760px){.chat-admin-shell{grid-template-columns:1fr}.chat-list{max-height:260px;overflow:auto}}</style>@endpush
@endsection
